openapi: 3.0.2

info:
  title: Sort Portfolio API
  version: 1.0.0

servers:
  - url: /

paths:
  /health:
    get:
      responses:
        "200":
          description: OK

  /api/run-battle:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RunBattleRequest"
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request

  /api/battles:
    get:
      responses:
        "200":
          description: OK

  /api/statistics:
    get:
      responses:
        "200":
          description: OK

components:
  schemas:
    RunBattleRequest:
      type: object
      required:
        - array_size
      properties:
        array_size:
          type: integer